logging:
  level:
    org:
      glifery:
        smarthome:
          adapter: INFO
          application:
            event:
              listener: WARN
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO

application:
  direct_megad_response: false
  double_click_milliseconds: 1000
  hold_click_milliseconds: 1000
  autoupdate_port_state_disabled: false
  autoupdate_port_state_seconds: 10

spreadsheet:
  credentials_json: "/google-sheets-client-secret.json"
  tokens_folder: "google-tokens"
  spreadsheet_id: "1TZ8a0feF8jdzMBiSrwdGJdtpIfKz3vUwDmDhnUCYsuI"
  spreadsheet_tab: "Подключение"
  tab: 2
  megad_port_column: I
  megad_action_column: J
  disabled: false

megad:
  common:
    password: sec
  controllers:
    megad1:
      host: http://192.168.0.141
      name: Megad1
      spreadsheet:
        first_row_for_p0: 8
    megad2:
      host: http://192.168.0.142
      name: Megad2
      spreadsheet:
        first_row_for_p0: 42